export function buildGatewayConfigTemplate(stateDbPath: string): string {
    return [
        "# Opencode Gateway configuration",
        "# Fill in secrets and provider details before enabling real integrations.",
        "",
        "[gateway]",
        `state_db = "${escapeTomlString(stateDbPath)}"`,
        '# log_level = "warn"',
        "",
        "# Gateway-owned external HTTP requests use HTTP_PROXY, HTTPS_PROXY, and",
        "# NO_PROXY by default. Disable this if your environment proxy should not",
        "# affect Telegram polling, delivery, and file downloads.",
        "# [gateway.http_proxy]",
        "# enabled = true",
        "",
        "# Optional mailbox settings.",
        "# [gateway.mailbox]",
        "# batch_replies = false",
        "# batch_window_ms = 1500",
        "#",
        "# Optional route overrides. Matching ingress targets can share one mailbox/session.",
        "# [[gateway.mailbox.routes]]",
        '# channel = "telegram"',
        '# target = "6212645712"',
        '# topic = "12345"',
        '# mailbox_key = "shared:telegram:dev"',
        "",
        "# Optional execution timeouts. Defaults are long-task friendly:",
        "# session_wait_timeout_ms = 1800000",
        "# prompt_progress_timeout_ms = 1800000",
        "# hard_timeout_ms is disabled by default, so complex jobs can run for hours",
        "# as long as they keep making progress.",
        "# [gateway.execution]",
        "# session_wait_timeout_ms = 1800000",
        "# prompt_progress_timeout_ms = 1800000",
        "# hard_timeout_ms = 7200000",
        "# abort_settle_timeout_ms = 5000",
        "",
        "# Optional policy for new inbound messages that arrive while the current",
        "# mailbox run is still executing.",
        "# [gateway.inflight_messages]",
        '# default_policy = "ask" # "ask" | "queue" | "interrupt"',
        "",
        "[cron]",
        "enabled = true",
        "tick_seconds = 5",
        "max_concurrent_runs = 1",
        '# timezone = "Asia/Shanghai"',
        "",
        "[channels.telegram]",
        "enabled = false",
        "# Ask @BotFather for the bot token. Choose exactly one credential source.",
        '# bot_token = "123456:ABCDEF"',
        "# Or load it from an environment variable:",
        'bot_token_env = "TELEGRAM_BOT_TOKEN"',
        "poll_timeout_seconds = 25",
        "# Configure at least one allowlist when Telegram is enabled.",
        "# Ask @userinfobot for your numeric Telegram user id for private-chat allowlists.",
        "allowed_chats = []",
        "allowed_users = []",
        "",
        "[channels.telegram.ux]",
        '# tool_call_view = "toggle" # "toggle" | "inline" | "off"',
        "# compaction_reaction = true",
        '# compaction_reaction_emoji = "🗜️"',
        "",
        "# Optional long-lived memory sources injected into gateway-managed sessions.",
        "# Relative paths are resolved from opencode-gateway-workspace.",
        "# Missing files and directories are created automatically.",
        "# The workspace also prepares `.opencode/skills/` for workspace-local OpenCode skills.",
        "#",
        "[[memory.entries]]",
        'path = "USER.md"',
        'description = "Persistent user profile and preference memory. Keep this file accurate and concise. Record stable preferences, communication style, workflow habits, project conventions, tool constraints, review expectations, and other recurring facts that should shape future assistance. Update it proactively when you learn something durable about the user. Do not store one-off task details or transient context here."',
        "inject_content = true",
        "",
        "[[memory.entries]]",
        'path = "RULES.md"',
        'description = "Behavior rules and standing operating constraints for the assistant. Keep this file concise, explicit, and current. Use it for durable expectations about behavior, review standards, output style, safety boundaries, and other rules that should consistently shape future responses. Update it proactively when new long-lived rules or boundaries become clear."',
        "inject_content = true",
        "",
        "[[memory.entries]]",
        'path = "memory/daily"',
        'description = "Daily notes stored as YYYY-MM-DD.md files. Use this directory for dated logs, short-lived findings, and day-specific working context that should remain searchable without being auto-injected. Create or update the current day\'s file proactively when meaningful new day-specific context appears."',
        "search_only = true",
        "",
        "# [[memory.entries]]",
        '# path = "memory/project.md"',
        '# description = "Project conventions and long-lived context"',
        '# header = "<important>"',
        '# footer = "</important>"',
        "# inject_content = true",
        "",
        "# [[memory.entries]]",
        '# path = "memory/notes"',
        '# description = "Domain notes and operating docs. Use memory_search and memory_get to inspect this directory on demand."',
        '# header = "<reference>"',
        '# footer = "</reference>"',
        "# search_only = true",
        "",
        "# [[memory.entries]]",
        '# path = "memory/snippets"',
        '# description = "Selected files are auto-injected; the rest stay searchable on demand."',
        '# globs = ["**/*.md", "notes/**/*.txt"]',
        "",
    ].join("\n")
}

function escapeTomlString(value: string): string {
    return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')
}
