export function buildGatewayConfigTemplate(stateDbPath: string): string {
    return [
        "# Opencode Gateway configuration",
        "# Fill in secrets and provider details before enabling real integrations.",
        "",
        "[gateway]",
        `state_db = "${escapeTomlString(stateDbPath)}"`,
        '# log_level = "warn"',
        "",
        "# Optional mailbox settings.",
        "# [gateway.mailbox]",
        "# batch_replies = false",
        "# batch_window_ms = 1500",
        "#",
        "# Optional route overrides. Matching ingress targets can share one mailbox/session.",
        "# [[gateway.mailbox.routes]]",
        '# channel = "telegram"',
        '# target = "6212645712"',
        '# topic = "12345"',
        '# mailbox_key = "shared:telegram:dev"',
        "",
        "[cron]",
        "enabled = true",
        "tick_seconds = 5",
        "max_concurrent_runs = 1",
        '# timezone = "Asia/Shanghai"',
        "",
        "[channels.telegram]",
        "enabled = false",
        'bot_token_env = "TELEGRAM_BOT_TOKEN"',
        "poll_timeout_seconds = 25",
        "# Configure at least one allowlist when Telegram is enabled.",
        "allowed_chats = []",
        "allowed_users = []",
        "",
        "# Optional long-lived memory sources injected into gateway-managed sessions.",
        "# Relative paths are resolved from opencode-gateway-workspace.",
        "# Missing files and directories are created automatically.",
        "#",
        "[[memory.entries]]",
        'path = "USER.md"',
        'description = "Persistent user profile and preference memory. Keep this file accurate and concise. Record stable preferences, communication style, workflow habits, project conventions, tool constraints, review expectations, and other recurring facts that should shape future assistance. Update it proactively when you learn something durable about the user. Do not store one-off task details or transient context here."',
        "inject_content = true",
        "#",
        "# [[memory.entries]]",
        '# path = "memory/project.md"',
        '# description = "Project conventions and long-lived context"',
        "# inject_content = true",
        "#",
        "# [[memory.entries]]",
        '# path = "memory/notes"',
        '# description = "Domain notes and operating docs. Use memory_search and memory_get to inspect this directory on demand."',
        "# search_only = true",
        "#",
        "# [[memory.entries]]",
        '# path = "memory/snippets"',
        '# description = "Selected files are auto-injected; the rest stay searchable on demand."',
        '# globs = ["**/*.md", "notes/**/*.txt"]',
        "",
    ].join("\n")
}

function escapeTomlString(value: string): string {
    return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')
}
